/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as ApiFilesFileIdRouteImport } from './routes/api.files.$fileId'
import { Route as ApiFilesCleanupRouteImport } from './routes/api.files.cleanup'
import { Route as ApiFilesUploadsRouteImport } from './routes/api.files.uploads'
import { Route as ApiFilesFileIdCompleteRouteImport } from './routes/api.files.$fileId.complete'
import { Route as ApiFilesFileIdCopiesRouteImport } from './routes/api.files.$fileId.copies'
import { Route as ApiFilesFileIdDownloadRouteImport } from './routes/api.files.$fileId.download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesCleanupRoute = ApiFilesCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesUploadsRoute = ApiFilesUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesFileIdCompleteRoute = ApiFilesFileIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdCopiesRoute = ApiFilesFileIdCopiesRouteImport.update({
  id: '/copies',
  path: '/copies',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdDownloadRoute = ApiFilesFileIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/files'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/files'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
  id:
    | '__root__'
    | '/'
    | '/api/files'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/cleanup': {
      id: '/api/files/cleanup'
      path: '/cleanup'
      fullPath: '/api/files/cleanup'
      preLoaderRoute: typeof ApiFilesCleanupRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/uploads': {
      id: '/api/files/uploads'
      path: '/uploads'
      fullPath: '/api/files/uploads'
      preLoaderRoute: typeof ApiFilesUploadsRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/$fileId/complete': {
      id: '/api/files/$fileId/complete'
      path: '/complete'
      fullPath: '/api/files/$fileId/complete'
      preLoaderRoute: typeof ApiFilesFileIdCompleteRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/copies': {
      id: '/api/files/$fileId/copies'
      path: '/copies'
      fullPath: '/api/files/$fileId/copies'
      preLoaderRoute: typeof ApiFilesFileIdCopiesRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/download': {
      id: '/api/files/$fileId/download'
      path: '/download'
      fullPath: '/api/files/$fileId/download'
      preLoaderRoute: typeof ApiFilesFileIdDownloadRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
  }
}

interface ApiFilesFileIdRouteChildren {
  ApiFilesFileIdCompleteRoute: typeof ApiFilesFileIdCompleteRoute
  ApiFilesFileIdCopiesRoute: typeof ApiFilesFileIdCopiesRoute
  ApiFilesFileIdDownloadRoute: typeof ApiFilesFileIdDownloadRoute
}

const ApiFilesFileIdRouteChildren: ApiFilesFileIdRouteChildren = {
  ApiFilesFileIdCompleteRoute: ApiFilesFileIdCompleteRoute,
  ApiFilesFileIdCopiesRoute: ApiFilesFileIdCopiesRoute,
  ApiFilesFileIdDownloadRoute: ApiFilesFileIdDownloadRoute,
}

const ApiFilesFileIdRouteWithChildren = ApiFilesFileIdRoute._addFileChildren(
  ApiFilesFileIdRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRouteWithChildren
  ApiFilesCleanupRoute: typeof ApiFilesCleanupRoute
  ApiFilesUploadsRoute: typeof ApiFilesUploadsRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdRoute: ApiFilesFileIdRouteWithChildren,
  ApiFilesCleanupRoute: ApiFilesCleanupRoute,
  ApiFilesUploadsRoute: ApiFilesUploadsRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
