/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiFoldersRouteImport } from './routes/api.folders'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api.openapi[.]json'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as ApiFilesFileIdRouteImport } from './routes/api.files.$fileId'
import { Route as ApiFilesCleanupRouteImport } from './routes/api.files.cleanup'
import { Route as ApiFilesUploadsRouteImport } from './routes/api.files.uploads'
import { Route as ApiFilesFileIdCompleteRouteImport } from './routes/api.files.$fileId.complete'
import { Route as ApiFilesFileIdCopiesRouteImport } from './routes/api.files.$fileId.copies'
import { Route as ApiFilesFileIdDownloadRouteImport } from './routes/api.files.$fileId.download'
import { Route as ApiFilesFileIdEmbeddingsRetryRouteImport } from './routes/api.files.$fileId.embeddings.retry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiRoute,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApiRoute,
} as any)
const ApiFoldersRoute = ApiFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => ApiRoute,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => ApiRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesCleanupRoute = ApiFilesCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesUploadsRoute = ApiFilesUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiFilesFileIdCompleteRoute = ApiFilesFileIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdCopiesRoute = ApiFilesFileIdCopiesRouteImport.update({
  id: '/copies',
  path: '/copies',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdDownloadRoute = ApiFilesFileIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdEmbeddingsRetryRoute =
  ApiFilesFileIdEmbeddingsRetryRouteImport.update({
    id: '/embeddings/retry',
    path: '/embeddings/retry',
    getParentRoute: () => ApiFilesFileIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/embeddings/retry': typeof ApiFilesFileIdEmbeddingsRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/embeddings/retry': typeof ApiFilesFileIdEmbeddingsRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/api/files/cleanup': typeof ApiFilesCleanupRoute
  '/api/files/uploads': typeof ApiFilesUploadsRoute
  '/api/files/$fileId/complete': typeof ApiFilesFileIdCompleteRoute
  '/api/files/$fileId/copies': typeof ApiFilesFileIdCopiesRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/embeddings/retry': typeof ApiFilesFileIdEmbeddingsRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/api/chat'
    | '/api/files'
    | '/api/folders'
    | '/api/openapi.json'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/embeddings/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/api/chat'
    | '/api/files'
    | '/api/folders'
    | '/api/openapi.json'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/embeddings/retry'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/api/chat'
    | '/api/files'
    | '/api/folders'
    | '/api/openapi.json'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/files/$fileId'
    | '/api/files/cleanup'
    | '/api/files/uploads'
    | '/api/files/$fileId/complete'
    | '/api/files/$fileId/copies'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/embeddings/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/files': {
      id: '/api/files'
      path: '/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/folders': {
      id: '/api/folders'
      path: '/folders'
      fullPath: '/api/folders'
      preLoaderRoute: typeof ApiFoldersRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof ApiRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/cleanup': {
      id: '/api/files/cleanup'
      path: '/cleanup'
      fullPath: '/api/files/cleanup'
      preLoaderRoute: typeof ApiFilesCleanupRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/uploads': {
      id: '/api/files/uploads'
      path: '/uploads'
      fullPath: '/api/files/uploads'
      preLoaderRoute: typeof ApiFilesUploadsRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/files/$fileId/complete': {
      id: '/api/files/$fileId/complete'
      path: '/complete'
      fullPath: '/api/files/$fileId/complete'
      preLoaderRoute: typeof ApiFilesFileIdCompleteRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/copies': {
      id: '/api/files/$fileId/copies'
      path: '/copies'
      fullPath: '/api/files/$fileId/copies'
      preLoaderRoute: typeof ApiFilesFileIdCopiesRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/download': {
      id: '/api/files/$fileId/download'
      path: '/download'
      fullPath: '/api/files/$fileId/download'
      preLoaderRoute: typeof ApiFilesFileIdDownloadRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/embeddings/retry': {
      id: '/api/files/$fileId/embeddings/retry'
      path: '/embeddings/retry'
      fullPath: '/api/files/$fileId/embeddings/retry'
      preLoaderRoute: typeof ApiFilesFileIdEmbeddingsRetryRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
  }
}

interface ApiFilesFileIdRouteChildren {
  ApiFilesFileIdCompleteRoute: typeof ApiFilesFileIdCompleteRoute
  ApiFilesFileIdCopiesRoute: typeof ApiFilesFileIdCopiesRoute
  ApiFilesFileIdDownloadRoute: typeof ApiFilesFileIdDownloadRoute
  ApiFilesFileIdEmbeddingsRetryRoute: typeof ApiFilesFileIdEmbeddingsRetryRoute
}

const ApiFilesFileIdRouteChildren: ApiFilesFileIdRouteChildren = {
  ApiFilesFileIdCompleteRoute: ApiFilesFileIdCompleteRoute,
  ApiFilesFileIdCopiesRoute: ApiFilesFileIdCopiesRoute,
  ApiFilesFileIdDownloadRoute: ApiFilesFileIdDownloadRoute,
  ApiFilesFileIdEmbeddingsRetryRoute: ApiFilesFileIdEmbeddingsRetryRoute,
}

const ApiFilesFileIdRouteWithChildren = ApiFilesFileIdRoute._addFileChildren(
  ApiFilesFileIdRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRouteWithChildren
  ApiFilesCleanupRoute: typeof ApiFilesCleanupRoute
  ApiFilesUploadsRoute: typeof ApiFilesUploadsRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdRoute: ApiFilesFileIdRouteWithChildren,
  ApiFilesCleanupRoute: ApiFilesCleanupRoute,
  ApiFilesUploadsRoute: ApiFilesUploadsRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

interface ApiRouteChildren {
  ApiChatRoute: typeof ApiChatRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiFoldersRoute: typeof ApiFoldersRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiChatRoute: ApiChatRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiFoldersRoute: ApiFoldersRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
